name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python-ci:
    uses: OnYyon/oregon-ci-templates/.github/workflows/lint-python.yml@main
    with:
      python-version: "3.14"
      test-command: "pytest"
      test-path: "./tests"
      coverage-threshold: 80
